helpers/set-configure-ac-version.sh

This allows us to drop the gen-version hacks in sdisted tarballs.

Add a configure.ac modifying script

---

helpers/build-specs.sh

Add `set -e` to build-specs.sh so that we exit when one of the helpers
fails, which happens when python3 is not installed.

build-specs.sh: add set -e

---

build.sh

Prefix Docker steps with a relative timestamp like `[ 0:23]` in normal
progress output mode (no -v) to make it easier to spot slow build steps.

Prefix Docker steps with relative timestamp

---

.gitignore
build.sh
helpers/build-specs.sh

A new `-c` option will enable rpm build caching per spec. This is
currently only suitable for vendor packages, because it determines
changes by the hash of the spec file only
This mechanism can be extended later to specs that depend on source
packages by hashing their contents.
To use this, you need to add the following to your RPM build
Dockerfiles:
@IF [ ! -z "$BUILDER_CACHE" ]
@EVAL ADD builder/cache/${BUILDER_TARGET}/ /cache/old/
ENV BUILDER_CACHE 1
@ENDIF
and set `BUILDER_CACHE_THIS=1` on the build-specs.sh lines where
you want to enable this.

RPM build caching

---

build.sh

In addition to the build steps, output all lines starting with '::: ' in progress output mode (the default).

Special '::: ' output prefix

---

.travis.yml
gen-version
helpers/build-debs.sh
helpers/build-rocks.sh
helpers/build-specs.sh
helpers/functions.sh
tests/test_versioning.sh

When tagging e.g. with `1.2.3-alpha1`, the rpms and debian packages will follow the following conventions (when `IS_RELEASE=YES`:
* RPM: `1.2.3-0.alpha1.$BUILDER_RELEASE`
* DEB: `1.2.3~alpha1-$BUILDER_RELEASE`
When IS_RELEASE is not set, the following is used:
* RPM: `1.2.3-0.alpha1.$COMMITS_SINCE_TAG.$GIT_HASH.$BUILDER_RELEASE`
* DEB: `1.2.3~alpha1-0.$COMMITS_SINCE_TAG.$GIT_HASH.$BUILDER_RELEASE`

Create package version when using pre-releases

---

demo/builder-support/dockerfiles/Dockerfile.target.centos-7
helpers/build-debs.sh

This ensures we properly get the distribution name when /etc/os-release
does not have VERSION set, attempt to get the release from PRETTY_NAME,
which is set to `Debian GNU/Linux $upcoming_release/sid`.

Support debian pre-releases

---

demo/builder-support/dockerfiles/Dockerfile.target.centos-7

`python34` no longer installs `/usr/bin/python3`. (`python36` does now, but this change is future proof)

centos demo build: ask for any python3

---

build.sh

This allows the gen-version in builder-support to make decisions based
on the enabled modules.

Expose the enabled modules to custom gen-version

---

.travis.yml
build.sh
demo/builder-support/dockerfiles/Dockerfile.target.sdist

Spaces inside values are not supported, but this will allow users to send any kind of argument to the builds.

Add option to pass build arguments to docker

---

build.sh

Investigating some issues with the `yum` command being very slow in the official `centos:7` images, we've discovered that by default, docker sets a very high number for the `nofile` file ulimit
```bash
% docker run --rm centos:7 bash -c "ulimit -a"
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30578
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1073741816
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time …
```

Add a new flag to override the default docker build ulimits

---

gen-version

Projects that tag with vX.Y.Z will get correct version numbers this way

Strip a leading 'v' in the version number

---

build.sh

Without this change, the builder would not exit when invoked with `IS_RELEASE=YES` while not on a commit.

Actually stop the build when version cannot be determined

---

Dockerfile-kaniko
build.sh

This adds support for running pdns-builder with [kaniko](https://github.com/GoogleContainerTools/kaniko) instead of docker. This is required when the CI running is on k8s and docker-in-docker is not available (e.g. because the cluster uses runc, the cluster admin does not want privileged containers or the docker socket can't be exposed).
The kaniko executor must be available at /kaniko/executor. A dockerfile is added to build an Alpine image that has the executor and the minimal set of dependencies required for pdns-builder to run.
To use kaniko, the `-K` must be passed to build.sh.
Kaniko can cache layers to a registry. To accomplish this, the `-k URL` flag can be set.
An example of how to use this within GitLab-CI looks like this:
```yaml
CentOS 7 pkg:
image:
name: …
```

Add Kaniko support to the builder

---

helpers/build-debs.sh

DEB_BUILD_OPTIONS must be set to a value greater than '1' for the debhelper to invoke 'make' with multiple job support.
This change results in the same behavior exhibited by RPM builds (where parallelism is used by default).

Enable parallelism for builds of Debian packages

---

.travis.yml
README.md
build.sh
demo/README.md
demo/builder-support/dockerfiles/Dockerfile.rpmbuild
demo/builder-support/dockerfiles/Dockerfile.target.centos-8
demo/builder-support/dockerfiles/Dockerfile.target.sdist
helpers/build-specs.sh
tests/test-centos-8-reproducible.sh

Reproducible RPM builds and `SOURCE_DATE_EPOCH` env var.
Note that this only works for RHEL 8+ and derived distributions, as the RPM version in RHEL 7 does not support reproducible builds.
Progress

Reproducible RPM builds

---

demo/builder-support/dockerfiles/Dockerfile.target.sdist

Unix timestamps must be prefixed with an `@` for `tar --mtime`.
See https://www.gnu.org/software/tar/manual/html_section/Date-input-formats.html#Date-input-formats

demo: fix tar --mtime format

---

build.sh
helpers/functions.sh
tests/test_versioning.sh

Make `BUILDER_PYTHON_SRC_VERSION` [PEP 440](https://peps.python.org/pep-0440/) compliant, and pass it as a build arg.
Setuptools 66 (Jan 2023) turned version format warnings into errors, breaking builds.
See https://github.com/pypa/setuptools/issues/3772 for more information
To fix Python builds:
- Add `ARG BUILDER_PYTHON_SRC_VERSION` to your Dockerfile
- You can also add `RUN test -n "$BUILDER_PYTHON_SRC_VERSION"` to check that it is actually set
- Use `BUILDER_PYTHON_SRC_VERSION` instead of `BUILDER_VERSION` as your package version in `setup.py` (do not read the env var from there, but write it to a `version.txt` that is explicitly packaged in your `MANIFEST.in`, and read that file)

PEP 440 compliant Python BUILDER_PYTHON_SRC_VERSION

---

helpers/build-debs.sh

On older Debian/Ubuntu it gets installed, and dpkg-buildpackage should use it. On newer versions, we do not need it.
For further reading, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041150

Stop explicitly requiring fakeroot

---

helpers/generate-dnf-provenance.py

This PR changes two files. *Either* change fixes the problem (`import dnf` failing in the provenance script), so we need to choose.

use platform-python for dnf provenance generation

---

.github/workflows/tests.yml
demo/builder-support/dockerfiles/Dockerfile.target.rocky-9
tests/test-rocky-9-reproducible.sh

may need a rebase if #70 changes

add rocky 9 testing

---

helpers/build-debs.sh

this fixes https://github.com/PowerDNS/pdns/issues/11925
debianXX sorts after the currently popular codenames (bullseye, bookworm)
ubuntuXX.YY sorts after all ubuntu releases since 15.04
tested on
* ubuntu trusty 14.04 (ubuntu14.04)
* ubuntu jammy 22.04 (ubuntu22.04)
* debian bookworm 12 (debian12)
* debian testing (debian13) - this requires distro-info-data

build-debs: prefer [distro][number] over distribution codenames
